title: João Faraco
baseurl: "/joaofaraco" # the subpath of your site, e.g. /blog
url: "https://jpfaraco.github.io" # the base hostname & protocol for your site, e.g. http://example.com
sass:
  style: compact
